version: '2'

services:
  server:
    build: ./server
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "32000:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  client:
    build: ./client
    ports:
      - "5005:5005"
    tty: true
    stdin_open: true

  admin:
    build: ./admin
    links:
      - db
    ports:
      - "5010:5010"
    depends_on:
      - db
    tty: true
    stdin_open: true

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    user: "0"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - db

volumes:
    grafana_data: {}

