version: '3'

services:
  server:
    image: loredanasoare/cfr_calatori:server
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  client:
    image: loredanasoare/cfr_calatori:client
    ports:
      - "5005:5005"
    tty: true
    stdin_open: true

  admin:
    image: loredanasoare/cfr_calatori:admin
    ports:
      - "5010:5010"
    depends_on:
      - db
    tty: true
    stdin_open: true

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    user: "0"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - db

volumes:
    db_data: {}
    grafana_data: {}

