version: '3.7'
services:
  app:
    build: ./app
    links:
      - mysql_db
    ports:
      - "5000:5000"
  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'CFR'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'lori!'
      MYSQL_ROOT_PASSWORD: 'lori!'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_db_data:/var/lib/mysql
volumes:
  mysql_db_data:
